import os
import json
import boto3
import base64
import asyncio
from datetime import datetime, timedelta, timezone
from typing import Dict, Optional
from atproto import Client
from atproto_client.models.app.bsky.feed.search_posts import Params as SearchParams

# Patch pathlib BEFORE importing pyppeteer to prevent /home directory access
import pathlib
_original_expanduser = pathlib.Path.expanduser

def _patched_expanduser(self):
    # Return /tmp directly instead of calling original
    return pathlib.Path('/tmp')

pathlib.Path.expanduser = _patched_expanduser

# Set environment for pyppeteer
os.environ['HOME'] = '/tmp'
os.environ['TMPDIR'] = '/tmp'
os.environ['PYPPETEER_HOME'] = '/opt/chromium-cache/pyppeteer'

from pyppeteer import launch

# AWS Clients
s3_client = boto3.client('s3')
secrets_client = boto3.client('secretsmanager')

# JST timezone
JST = timezone(timedelta(hours=9))

# === Configuration ===
S3_BUCKET = os.environ.get('S3_BUCKET', 'bluesky-sigma-showcase-878311109818')
S3_PREFIX = os.environ.get('S3_PREFIX', 'sigma-graph/')



# === Helper Functions ===
def get_jst_now():
    """Get current time in JST"""
    return datetime.now(JST)


def get_bluesky_credentials() -> Optional[Dict]:
    """Get Bluesky credentials from Secrets Manager"""
    try:
        response = secrets_client.get_secret_value(
            SecretId='bluesky-feed-jp/credentials'
        )
        return json.loads(response['SecretString'])
    except Exception as e:
        print(f"[SECRETS] Failed to get credentials: {str(e)}")
        return None


def build_response(status_code: int, body: Dict) -> Dict:
    """Build API response with CORS headers"""
    return {
        "statusCode": status_code,
        "headers": {
            "Content-Type": "application/json",
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Headers": "Content-Type,Authorization",
            "Access-Control-Allow-Methods": "GET,OPTIONS",
        },
        "body": json.dumps(body, ensure_ascii=False)
    }


def get_graph_from_s3(s3_key: str) -> Optional[Dict]:
    """
    Fetch graph JSON from S3.

    Args:
        s3_key: S3 object key

    Returns:
        Graph JSON dict or None if not found
    """
    try:
        response = s3_client.get_object(Bucket=S3_BUCKET, Key=s3_key)
        body = response['Body'].read().decode('utf-8')
        return json.loads(body)
    except s3_client.exceptions.NoSuchKey:
        print(f"[S3] Key not found: {s3_key}")
        return None
    except Exception as e:
        print(f"[S3 ERROR] Failed to fetch {s3_key}: {str(e)}")
        return None


def list_hashtags_deprecated() -> list:
    """
    DEPRECATED: Hashtag list is now generated by graph_crawler and served via CloudFront.
    This function is kept for reference only.

    List all available hashtags in S3.
    Returns only unified_* categories.

    Returns:
        List of hashtag names
    """
    try:
        paginator = s3_client.get_paginator('list_objects_v2')
        pages = paginator.paginate(
            Bucket=S3_BUCKET,
            Prefix=S3_PREFIX,
            Delimiter='/'
        )

        hashtags = []
        for page in pages:
            if 'CommonPrefixes' in page:
                for prefix in page['CommonPrefixes']:
                    # Extract hashtag from prefix (e.g., "sigma-graph/おはようvtuber/" -> "おはようvtuber")
                    hashtag = prefix['Prefix'].replace(S3_PREFIX, '').rstrip('/')
                    if hashtag:
                        # Only allow unified_* categories
                        if hashtag.startswith('unified_'):
                            hashtags.append(hashtag)

        return sorted(hashtags)
    except Exception as e:
        print(f"[S3 ERROR] Failed to list hashtags: {str(e)}")
        return []


# === API Handlers ===
async def generate_share_image_with_puppeteer(display_name: str, handle: str, avatar_url: str,
                                               follower_count: str, follows_count: str, posts_count: str,
                                               rank: str, graph_name: str, snapshot_time: str) -> bytes:
    """
    Generate share image using Puppeteer (HTML + CSS rendering).
    Puppeteer uses Chromium browser, which natively supports emoji rendering.

    Returns:
        PNG image as bytes
    """
    # Determine font paths
    font_dir = '/opt/python/fonts'  # Lambda layer location
    noto_sans_jp_path = f'{font_dir}/NotoSansJP-VariableFont_wght.ttf'
    noto_emoji_path = f'{font_dir}/NotoColorEmoji-Regular.ttf'

    # Fallback to system fonts if not in layer
    if not os.path.exists(noto_sans_jp_path):
        noto_sans_jp_path = '/usr/share/fonts/opentype/noto/NotoSansJP-Regular.otf'
    if not os.path.exists(noto_emoji_path):
        noto_emoji_path = '/usr/share/fonts/opentype/noto/NotoColorEmoji-Regular.ttf'

    # Convert to data: URLs for CSS
    def font_to_data_url(font_path: str) -> str:
        """Convert font file to data URL"""
        if not os.path.exists(font_path):
            print(f"[FONT] Warning: Font not found: {font_path}")
            return ""
        try:
            with open(font_path, 'rb') as f:
                font_data = base64.b64encode(f.read()).decode('utf-8')
            return f"data:font/ttf;base64,{font_data}"
        except Exception as e:
            print(f"[FONT] Error reading {font_path}: {e}")
            return ""

    noto_sans_jp_url = font_to_data_url(noto_sans_jp_path)
    noto_emoji_url = font_to_data_url(noto_emoji_path)

    # Calculate dynamic font size based on display name length
    name_length = len(display_name)
    if name_length <= 10:
        display_name_size = 60
    elif name_length <= 25:
        display_name_size = 45
    else:
        display_name_size = 32

    # Calculate star emoji based on rank digits
    rank_int = int(rank)
    if rank_int < 10:
        star_emoji = "⭐⭐⭐"
    elif rank_int < 100:
        star_emoji = "⭐⭐"
    elif rank_int < 1000:
        star_emoji = "⭐"
    else:
        star_emoji = ""

    # HTML template with CSS
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            @font-face {{
                font-family: 'Noto Sans JP';
                src: url('{noto_sans_jp_url}') format('truetype');
            }}
            @font-face {{
                font-family: 'Noto Color Emoji';
                src: url('{noto_emoji_url}') format('truetype');
            }}
            * {{
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }}
            body {{
                width: 1200px;
                height: 630px;
                background: linear-gradient(45deg, white 0%, white 70%, #0099CC 100%);
                font-family: "Noto Sans JP", "Noto Color Emoji", sans-serif;
                display: flex;
                flex-direction: column;
                justify-content: flex-start;
                padding: 50px 30px 80px 30px;
                position: relative;
                box-sizing: border-box;
            }}
            .container {{
                display: flex;
                gap: 20px;
                align-items: flex-start;
            }}
            .avatar {{
                width: 180px;
                height: 180px;
                border-radius: 50%;
                object-fit: cover;
                flex-shrink: 0;
            }}
            .content {{
                flex: 1;
                display: flex;
                flex-direction: column;
                gap: 15px;
            }}
            .display-name {{
                font-size: {display_name_size}px;
                font-weight: 900;
                color: #000;
                word-break: break-word;
                margin-right: 200px;
            }}
            .handle {{
                font-size: 32px;
                font-weight: 400;
                color: #646464;
            }}
            .stats {{
                display: flex;
                flex-direction: column;
                gap: 10px;
                font-size: 40px;
                font-weight: 600;
                color: #3c3c3c;
            }}
            .rank {{
                font-size: 40px;
                font-weight: 700;
                color: #ff6b4a;
                margin-top: 10px;
            }}
            .footer {{
                position: absolute;
                bottom: 20px;
                left: 60px;
                right: 60px;
                display: flex;
                justify-content: flex-end;
                align-items: center;
                gap: 40px;
                font-size: 26px;
                font-weight: 400;
                color: #505050;
                box-sizing: border-box;
            }}
            .footer-left {{
                flex-shrink: 0;
                text-align: right;
                order: 3;
            }}
            .footer-right {{
                flex-shrink: 0;
                text-align: right;
                order: 2;
            }}
            .logo {{
                position: absolute;
                top: 45px;
                right: 45px;
                width: 150px;
                height: 150px;
                object-fit: contain;
            }}
        </style>
    </head>
    <body>
        <img class="logo" src="https://d1g3djqpjf3j38.cloudfront.net/bluesky_media_kit_logo_transparent_2.png" alt="logo" onerror="this.style.display='none'" />
        <div class="container">
            <img class="avatar" src="{avatar_url}" alt="avatar" onerror="this.style.display='none'" />
            <div class="content">
                <div class="display-name">{display_name}</div>
                <div class="handle">@{handle}</div>
                <div class="stats">
                    <div>Posts: {int(float(posts_count)):,}</div>
                    <div>Follows: {int(float(follows_count)):,}</div>
                    <div>Followers: {int(float(follower_count)):,}</div>
                </div>
                <div class="rank">{graph_name}  Rank #{rank} {star_emoji}</div>
            </div>
        </div>
        <div class="footer">
            <div class="footer-right">✨ Generated by Sky Star Cluster</div>
            <div class="footer-left">{snapshot_time}</div>
        </div>
    </body>
    </html>
    """

    browser = None
    try:
        # Launch Chromium with Puppeteer
        # Create necessary directories
        os.makedirs('/tmp/chromium-user-data', exist_ok=True)
        os.makedirs('/tmp/chromium-cache', exist_ok=True)

        # Find Chromium dynamically (may have different version)
        chromium_path = None
        chromium_base = '/opt/chromium-cache/pyppeteer/local-chromium'
        if os.path.exists(chromium_base):
            # Find any chrome binary under local-chromium/*/chrome-linux/chrome
            for version_dir in os.listdir(chromium_base):
                candidate = os.path.join(chromium_base, version_dir, 'chrome-linux', 'chrome')
                if os.path.exists(candidate):
                    chromium_path = candidate
                    print(f"[PUPPETEER] Found Chromium: {chromium_path}")
                    break

        browser = await launch(
            executablePath=chromium_path,
            headless=True,
            args=[
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--single-process',  # Reduce memory overhead
                '--user-data-dir=/tmp/chromium-user-data',
                '--cache-dir=/tmp/chromium-cache'
            ]
        )
        page = await browser.newPage()
        await page.setViewport({'width': 1200, 'height': 630})

        # Set content and render
        await page.setContent(html_content)

        # Take screenshot
        png_bytes = await page.screenshot({'type': 'png'})

        await page.close()
        await browser.close()

        return png_bytes

    except Exception as e:
        import traceback
        print(f"[PUPPETEER ERROR] {str(e)}")
        traceback.print_exc()
        if browser:
            try:
                await browser.close()
            except:
                pass
        raise


def handle_generate_share_image(query_params: Dict) -> Dict:
    """
    Handle GET /api/user/{handle}/share-image
    Generates a share image with user info, rank, graph name, and snapshot time.
    """
    try:
        display_name = query_params.get('displayName', 'Unknown')
        handle = query_params.get('handle', '')
        avatar_url = query_params.get('avatarUrl', '')
        follower_count = query_params.get('followerCount', '0')
        follows_count = query_params.get('followsCount', '0')
        posts_count = query_params.get('postsCount', '0')
        rank = query_params.get('rank', 'N/A')
        graph_name = query_params.get('graphName', 'Network')
        snapshot_time = query_params.get('snapshotTime', 'Unknown')

        # Run async function
        png_data = asyncio.run(generate_share_image_with_puppeteer(
            display_name=display_name,
            handle=handle,
            avatar_url=avatar_url,
            follower_count=str(follower_count),
            follows_count=str(follows_count),
            posts_count=str(posts_count),
            rank=str(rank),
            graph_name=graph_name,
            snapshot_time=snapshot_time
        ))

        # Return as base64-encoded PNG
        img_b64 = base64.b64encode(png_data).decode('utf-8')

        return {
            "statusCode": 200,
            "headers": {
                "Content-Type": "image/png",
                "Access-Control-Allow-Origin": "*",
                "Cache-Control": "max-age=3600"
            },
            "body": img_b64,
            "isBase64Encoded": True
        }

    except Exception as e:
        import traceback
        print(f"[IMAGE ERROR] Failed to generate share image: {str(e)}")
        traceback.print_exc()
        return build_response(500, {
            "error": "Failed to generate share image",
            "message": str(e)
        })


def handle_get_top_post(handle: str) -> Dict:
    """
    Handle GET /api/user/{handle}/top-post
    Fetches the top post for a user matching: lang:ja from:@{handle} sort:top limit:1

    Args:
        handle: Bluesky handle (without @)

    Returns:
        Top post data or error
    """
    try:
        # Initialize AT Protocol client
        client = Client()

        # Try to authenticate with credentials (optional)
        credentials = get_bluesky_credentials()
        if credentials:
            try:
                client.login(
                    login=credentials.get('handle'),
                    password=credentials.get('appPassword')
                )
                print(f"[API] Authenticated as {credentials.get('handle')}")
            except Exception as auth_err:
                print(f"[API] Could not authenticate: {str(auth_err)}")
                print("[API] Proceeding with unauthenticated client...")
        else:
            print("[API] No credentials found, proceeding with unauthenticated client...")

        # Build search query (exclude mentions)
        query = f"lang:ja from:{handle} -mentions"

        print(f"[API] Searching for top post: {query}")

        # Search for posts with sort parameter
        search_params = SearchParams(q=query, limit=1, sort='top')
        response = client.app.bsky.feed.search_posts(search_params)

        if not response.posts or len(response.posts) == 0:
            return build_response(404, {
                "error": "No posts found",
                "handle": handle,
                "message": f"No top posts found for @{handle}"
            })

        post = response.posts[0]

        # Filter out replies (posts with reply_parent)
        if hasattr(post.record, 'reply') and post.record.reply is not None:
            return build_response(404, {
                "error": "No posts found",
                "handle": handle,
                "message": f"No top posts found for @{handle}"
            })

        # Check if post has images
        has_images = False
        if hasattr(post, 'embed') and post.embed is not None:
            if hasattr(post.embed, 'images') and post.embed.images:
                has_images = True

        # Extract relevant post data
        post_data = {
            "uri": post.uri,
            "cid": post.cid,
            "author": {
                "handle": post.author.handle,
                "displayName": getattr(post.author, 'display_name', post.author.handle),
                "avatar": getattr(post.author, 'avatar', None),
            },
            "record": {
                "text": post.record.text,
                "createdAt": post.record.created_at if hasattr(post.record, 'created_at') else post.record.createdAt,
            },
            "likeCount": getattr(post, 'like_count', 0),
            "replyCount": getattr(post, 'reply_count', 0),
            "repostCount": getattr(post, 'repost_count', 0),
            "hasImages": has_images,
        }

        print(f"[API] Found top post for @{handle}")
        return build_response(200, post_data)

    except Exception as e:
        print(f"[API ERROR] Failed to fetch top post for @{handle}: {str(e)}")
        import traceback
        traceback.print_exc()
        return build_response(500, {
            "error": "Failed to fetch top post",
            "handle": handle,
            "message": str(e)
        })


def handle_options() -> Dict:
    """Handle CORS preflight request"""
    return {
        "statusCode": 200,
        "headers": {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Headers": "Content-Type,Authorization",
            "Access-Control-Allow-Methods": "GET,OPTIONS",
        },
        "body": ""
    }


# === Main Lambda Handler ===
def lambda_handler(event, context):
    """
    Main Lambda handler for user API.

    Routes:
    - GET /api/user/{handle}/top-post → Top post for a user
    - GET /api/user/{handle}/share-image → Share image for a user
    - OPTIONS /* → CORS preflight

    Note:
    - Graph data (/sigma-graph/{hashtag}/latest) is served directly from S3 via CloudFront
    - Hashtags list (/api/hashtags) is served directly from S3 via CloudFront
    """
    print(f"[HANDLER] Event: {json.dumps(event)}")

    try:
        http_method = event.get('httpMethod', 'GET')
        path = event.get('path', '/')
        path_parameters = event.get('pathParameters')

        # Handle CORS preflight
        if http_method == 'OPTIONS':
            return handle_options()

        # Handle GET requests
        if http_method == 'GET':
            # Route: /api/user/{handle}/share-image
            if 'user' in path and 'share-image' in path:
                query_params = event.get('queryStringParameters', {}) or {}
                query_params['handle'] = path_parameters.get('handle') if path_parameters else ''
                return handle_generate_share_image(query_params)

            # Route: /api/user/{handle}/top-post
            elif 'user' in path and 'top-post' in path:
                handle = path_parameters.get('handle') if path_parameters else None
                if not handle:
                    return build_response(400, {
                        "error": "Bad request",
                        "message": "handle parameter required"
                    })
                return handle_get_top_post(handle)

            # Reject requests to other paths (should not reach Lambda)
            else:
                return build_response(404, {
                    "error": "Not found",
                    "path": path
                })

        # Method not allowed
        return build_response(405, {
            "error": "Method not allowed",
            "method": http_method
        })

    except Exception as e:
        print(f"[HANDLER ERROR] {str(e)}")
        import traceback
        traceback.print_exc()
        return build_response(500, {
            "error": "Internal server error",
            "message": str(e)
        })
